// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.26.1";

// src/lib/mcp/tools/get-leaderboard.ts
import { defineTool } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z } from "npm:zod@^3.25.76";

// src/lib/mcp/supabase.ts
import { createClient } from "npm:@supabase/supabase-js@^2.89.0";
function runtimeEnv(name) {
  const runtime = globalThis;
  return runtime.Deno?.env?.get?.(name) ?? runtime.process?.env?.[name];
}
function configuredEnv(names) {
  for (const name of names) {
    const value = runtimeEnv(name)?.trim();
    if (value) return value;
  }
  return void 0;
}
function supabaseProjectUrl() {
  const url = configuredEnv(["SUPABASE_URL", "VITE_SUPABASE_URL"]);
  if (!url) throw new Error("SUPABASE_URL (or VITE_SUPABASE_URL) is required");
  return url;
}
function supabasePublishableKey() {
  const direct = configuredEnv([
    "SUPABASE_PUBLISHABLE_KEY",
    "VITE_SUPABASE_PUBLISHABLE_KEY"
  ]);
  if (direct) return direct;
  const keyset = runtimeEnv("SUPABASE_PUBLISHABLE_KEYS");
  if (keyset) {
    try {
      const parsed = JSON.parse(keyset);
      if (parsed && typeof parsed === "object" && !Array.isArray(parsed)) {
        const keys = parsed;
        const key = [keys.default, ...Object.values(keys)].find((v) => typeof v === "string" && v.trim().startsWith("sb_publishable_"))?.trim();
        if (key) return key;
      }
    } catch {
    }
  }
  const legacy = configuredEnv(["SUPABASE_ANON_KEY", "VITE_SUPABASE_ANON_KEY"]);
  if (legacy) return legacy;
  throw new Error("SUPABASE_PUBLISHABLE_KEY, SUPABASE_PUBLISHABLE_KEYS, or SUPABASE_ANON_KEY is required");
}
function supabaseForUser(ctx) {
  const token = ctx.getToken();
  if (!token) throw new Error("supabaseForUser requires a verified OAuth token");
  return createClient(supabaseProjectUrl(), supabasePublishableKey(), {
    global: { headers: { Authorization: `Bearer ${token}` } },
    auth: { persistSession: false, autoRefreshToken: false }
  });
}

// src/lib/mcp/tools/get-leaderboard.ts
var get_leaderboard_default = defineTool({
  name: "get_leaderboard",
  title: "Get player leaderboard",
  description: "Ranked player leaderboard with total points, games played and average points per game.",
  inputSchema: {
    limit: z.number().int().min(1).max(50).default(20).describe("Max players to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("players").select("name, total_points, games_played").order("total_points", { ascending: false }).limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((p) => ({
      name: p.name,
      totalPoints: Number(p.total_points ?? 0),
      gamesPlayed: Number(p.games_played ?? 0),
      average: Number(p.games_played ?? 0) > 0 ? Number((Number(p.total_points ?? 0) / Number(p.games_played)).toFixed(2)) : 0
    })).sort((a, b) => b.average - a.average).map((r, i) => ({ rank: i + 1, ...r }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { players: rows }
    };
  }
});

// src/lib/mcp/tools/get-team-leaderboard.ts
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z2 } from "npm:zod@^3.25.76";
var get_team_leaderboard_default = defineTool2({
  name: "get_team_leaderboard",
  title: "Get doubles team leaderboard",
  description: "Ranked doubles teams with total points, games played and average points per game.",
  inputSchema: {
    limit: z2.number().int().min(1).max(50).default(20).describe("Max teams to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("team_stats").select("player1_name, player2_name, total_points, games_played").limit(limit ?? 20);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const rows = (data ?? []).map((t) => ({
      team: `${t.player1_name} & ${t.player2_name}`,
      totalPoints: Number(t.total_points ?? 0),
      gamesPlayed: Number(t.games_played ?? 0),
      average: Number(t.games_played ?? 0) > 0 ? Number((Number(t.total_points ?? 0) / Number(t.games_played)).toFixed(2)) : 0
    })).sort((a, b) => b.average - a.average).map((r, i) => ({ rank: i + 1, ...r }));
    return {
      content: [{ type: "text", text: JSON.stringify(rows, null, 2) }],
      structuredContent: { teams: rows }
    };
  }
});

// src/lib/mcp/tools/list-sessions.ts
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z3 } from "npm:zod@^3.25.76";
var list_sessions_default = defineTool3({
  name: "list_sessions",
  title: "List recorded sessions",
  description: "Recorded play sessions, newest first, with every game's teams, scores and winning side.",
  inputSchema: {
    limit: z3.number().int().min(1).max(20).default(5).describe("Number of sessions to return.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("session_games").select("*").order("session_date", { ascending: false }).order("game_number", { ascending: true }).limit(500);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byDate = /* @__PURE__ */ new Map();
    for (const g of data ?? []) {
      const key = String(g.session_date);
      if (!byDate.has(key)) byDate.set(key, []);
      byDate.get(key).push(g);
    }
    const sessions = [...byDate.entries()].slice(0, limit ?? 5).map(([date, games]) => ({
      sessionDate: date,
      games: (games ?? []).map((g) => ({
        gameNumber: g.game_number,
        teamA: [g.team_a_player1, g.team_a_player2].filter(Boolean),
        teamB: [g.team_b_player1, g.team_b_player2].filter(Boolean),
        teamAScore: g.team_a_score,
        teamBScore: g.team_b_score,
        winner: g.winner,
        format: Number(g.team_a_score ?? 0) + Number(g.team_b_score ?? 0) === 0 ? "Tug Of War" : "Scored"
      }))
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(sessions, null, 2) }],
      structuredContent: { sessions }
    };
  }
});

// src/lib/mcp/tools/get-player-stats.ts
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z4 } from "npm:zod@^3.25.76";
var get_player_stats_default = defineTool4({
  name: "get_player_stats",
  title: "Get player stats",
  description: "Detailed stats for one player by name: points, games, average, win/loss record and recent games.",
  inputSchema: {
    name: z4.string().trim().min(1).describe("Player name, e.g. 'Gerard'.")
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ name }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data: player, error: playerError } = await supabase.from("players").select("*").ilike("name", name).maybeSingle();
    if (playerError) return { content: [{ type: "text", text: playerError.message }], isError: true };
    if (!player) {
      return { content: [{ type: "text", text: `No player named "${name}" found.` }], isError: true };
    }
    const { data: games, error: gamesError } = await supabase.from("session_games").select("*").or(
      [
        `team_a_player1.eq.${player.name}`,
        `team_a_player2.eq.${player.name}`,
        `team_b_player1.eq.${player.name}`,
        `team_b_player2.eq.${player.name}`
      ].join(",")
    ).order("session_date", { ascending: false });
    if (gamesError) return { content: [{ type: "text", text: gamesError.message }], isError: true };
    let wins = 0;
    let losses = 0;
    const recent = (games ?? []).map((g) => {
      const onA = g.team_a_player1 === player.name || g.team_a_player2 === player.name;
      const team = onA ? "A" : "B";
      const won = g.winner === team;
      if (won) wins++;
      else losses++;
      return {
        sessionDate: g.session_date,
        gameNumber: g.game_number,
        partner: onA ? [g.team_a_player1, g.team_a_player2].find((p) => p && p !== player.name) ?? null : [g.team_b_player1, g.team_b_player2].find((p) => p && p !== player.name) ?? null,
        opponents: onA ? [g.team_b_player1, g.team_b_player2].filter(Boolean) : [g.team_a_player1, g.team_a_player2].filter(Boolean),
        score: `${g.team_a_score ?? 0}-${g.team_b_score ?? 0}`,
        result: won ? "W" : "L"
      };
    });
    const gamesPlayed = Number(player.games_played ?? 0);
    const result = {
      name: player.name,
      totalPoints: Number(player.total_points ?? 0),
      gamesPlayed,
      average: gamesPlayed > 0 ? Number((Number(player.total_points ?? 0) / gamesPlayed).toFixed(2)) : 0,
      wins,
      losses,
      winPercentage: wins + losses > 0 ? Number((wins / (wins + losses) * 100).toFixed(1)) : 0,
      recentGames: recent.slice(0, 10)
    };
    return {
      content: [{ type: "text", text: JSON.stringify(result, null, 2) }],
      structuredContent: result
    };
  }
});

// src/lib/mcp/tools/list-session-signups.ts
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.26.1";
var list_session_signups_default = defineTool5({
  name: "list_session_signups",
  title: "List session signups",
  description: "Who is signed up for upcoming sessions, including which of the 4 slots are taken.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("session_signups").select("session_date, slot_number, player_name").order("session_date", { ascending: true }).order("slot_number", { ascending: true });
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    const byDate = /* @__PURE__ */ new Map();
    for (const s of data ?? []) {
      const key = String(s.session_date);
      if (!byDate.has(key)) byDate.set(key, []);
      byDate.get(key).push({ slot: s.slot_number, player: s.player_name });
    }
    const sessions = [...byDate.entries()].map(([sessionDate, slots]) => ({
      sessionDate,
      slots,
      isFull: slots.length >= 4
    }));
    return {
      content: [{ type: "text", text: JSON.stringify(sessions, null, 2) }],
      structuredContent: { sessions }
    };
  }
});

// src/lib/mcp/tools/post-message.ts
import { defineTool as defineTool6 } from "npm:@lovable.dev/mcp-js@0.26.1";
import { z as z5 } from "npm:zod@^3.25.76";
var post_message_default = defineTool6({
  name: "post_message",
  title: "Post a message board message",
  description: "Post a message to the club message board as the signed-in user.",
  inputSchema: {
    content: z5.string().trim().min(1).max(1e3).describe("Message text to post.")
  },
  annotations: { readOnlyHint: false, destructiveHint: false, openWorldHint: false },
  handler: async ({ content }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "Not authenticated" }], isError: true };
    }
    const supabase = supabaseForUser(ctx);
    const { data, error } = await supabase.from("messages").insert({ user_id: ctx.getUserId(), content }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Posted: ${content}` }],
      structuredContent: { message: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "gapjwpmowinoebrhwfhk";
var mcp_default = defineMcp({
  name: "tkstl",
  title: "TKSTL",
  version: "0.1.0",
  instructions: "Tools for TKSTL, a tennis league club app. Read the player and doubles-team leaderboards, recorded session results, per-player stats and upcoming session signups, and post to the club message board. Points: scored games use the raw score, Tug of War awards 10 for a win and 5 for a loss; average = total points / games played.",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [
    get_leaderboard_default,
    get_team_leaderboard_default,
    list_sessions_default,
    get_player_stats_default,
    list_session_signups_default,
    post_message_default
  ]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.26.1/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
